plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace "com.martodosko.github.updater"
    compileSdk 34

    defaultConfig {
        applicationId "com.martodosko.github.updater"
        minSdk 24
        targetSdk 34
        versionCode 60004
        versionName "6.0.4"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
        debug {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    // ==============================================
    // ✅ PANGALAN NG APK — install-GitHubUpdater-vX.X.X.apk
    // ==============================================
    applicationVariants.all { variant ->
        variant.outputs.all { output ->
            output.outputFileName = "install-GitHubUpdater-v${variant.versionName}.apk"
        }
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.12.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.drawerlayout:drawerlayout:1.1.1'
}
